# Generated by Django 4.1.2 on 2022-10-11 08:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ts_created",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("ts_updated", models.DateTimeField(auto_now=True, db_index=True)),
                ("title", models.CharField(max_length=500, null=True)),
                ("video_url", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "description",
                    models.TextField(blank=True, max_length=50000, null=True),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
            ],
            options={"abstract": False,},
        ),
    ]
